import React, { useState, useEffect, useRef } from 'react';
import { Send, ArrowLeft, Bot, User, Code, FileText, Loader2, Copy, Check, Download, Cloud } from 'lucide-react';
import ReactMarkdown from 'react-markdown';
import { API_HOST, API_BASE } from '../utils/api';

export default function ExperimentDesign({ taskName, onBack }) {
    const [messages, setMessages] = useState([]);
    const [input, setInput] = useState('');
    const [isLoading, setIsLoading] = useState(false);
    const [codeTabs, setCodeTabs] = useState([]);
    const [activeTab, setActiveTab] = useState(0);
    const [copied, setCopied] = useState(false);
    const [scriptLoaded, setScriptLoaded] = useState(false);
    const [taskInfo, setTaskInfo] = useState(null);
    const [videoUrl, setVideoUrl] = useState(null);

    const messagesEndRef = useRef(null);
    const videoRef = useRef(null);

    const scrollToBottom = () => {
        messagesEndRef.current?.scrollIntoView({ behavior: "smooth" });
    };

    useEffect(() => {
        scrollToBottom();
    }, [messages]);

    // Load video URL on mount
    useEffect(() => {
        const fetchVideoUrl = async () => {
            try {
                const res = await fetch(`${API_BASE}/videos/library`);
                const data = await res.json();
                const video = data.videos?.find(v => v.task_name === taskName);
                if (video?.video_url) {
                    setVideoUrl(video.video_url);
                }
            } catch (e) {
                console.error('Failed to fetch video URL:', e);
            }
        };
        fetchVideoUrl();
    }, [taskName]);

    // Load generated training script on mount
    useEffect(() => {
        if (scriptLoaded) return;

        const loadGeneratedScript = async () => {
            try {
                // First, get the base training script
                const scriptRes = await fetch(`${API_BASE}/experiment/script/generate/${taskName}`);
                const scriptData = await scriptRes.json();

                // Then, get Gemini-generated reward function
                let rewardCode = '';
                let geminiGenerated = false;
                try {
                    const rewardRes = await fetch(`${API_BASE}/experiment/generate-reward/${taskName}`, {
                        method: 'POST'
                    });
                    const rewardData = await rewardRes.json();
                    rewardCode = rewardData.reward_code || '';
                    geminiGenerated = !rewardData.fallback;
                } catch (e) {
                    console.error('Gemini reward generation failed:', e);
                }

                const data = scriptData;

                if (data.train_code) {
                    setTaskInfo({
                        task_type: data.task_type,
                        reward_config: data.reward_config,
                        milestones: data.milestones
                    });

                    // Use modular code from backend
                    // If Gemini-generated reward is available, use it; otherwise use backend default
                    let finalRewardCode = data.reward_code;
                    if (rewardCode && !rewardCode.includes('TODO')) {
                        // Gemini generated something useful - wrap it in the reward.py format
                        const milestoneNames = (data.milestones || []).map(m => m.label);
                        finalRewardCode = `"""
Reward Function for: ${taskName}
Task Type: ${data.task_type}
Milestones: ${milestoneNames.join(', ') || 'none'}
${geminiGenerated ? '(Generated by Gemini - feel free to edit!)' : ''}
"""

import numpy as np
from config import REWARD_CONFIG, MILESTONES


def compute_reward(env, obs, action, info):
    data = env.unwrapped.data
    model = env.unwrapped.model

    # === GET STATE ===
    obj_pos = data.xpos[model.body("Object").id].copy()
    palm_pos = data.xpos[model.body("palm").id].copy()
    obj_height = obj_pos[2]
    hand_to_obj = np.linalg.norm(palm_pos - obj_pos)
    dist_to_target = np.linalg.norm(obj_pos - env.target_pos)
    obj_velocity = np.linalg.norm(data.qvel[-6:-3]) if len(data.qvel) > 6 else 0
    n_contacts = data.ncon

${rewardCode}
`;
                    }

                    // Create tabs with FULL modular code from backend
                    setCodeTabs([
                        { title: 'train.py', language: 'python', code: data.train_code },
                        { title: 'config.py', language: 'python', code: data.config_code },
                        { title: 'baseline.py', language: 'python', code: data.baseline_code },
                        { title: 'residual.py', language: 'python', code: data.residual_code },
                        { title: 'reward.py', language: 'python', code: finalRewardCode },
                    ]);
                    setActiveTab(0);

                    // Build context message
                    const milestonesInfo = data.milestones?.length > 0
                        ? data.milestones.map(m => `**${m.label}**: frame ${m.frame}`).join('\n\n')
                        : 'None detected';

                    // Replace loading message with full context
                    const generatedNote = geminiGenerated
                        ? `\n\n*Reward function generated by Gemini based on your milestones!*`
                        : `\n\n*Using template reward - ask me to customize it for your task!*`;

                    setMessages([{
                        role: 'model',
                        content: `Your **Residual RL** training files are ready! (${data.task_type} task)

**Pipeline:** Video → MediaPipe → Retarget → BC → Residual RL

**Detected Milestones:**

${milestonesInfo}

**Browse the code tabs:**

• **train.py** - Full pipeline (extract → BC → residual RL)
• **config.py** - ALL hyperparameters (BC, residual, reward)
• **baseline.py** - BC policy that learns from demo
• **residual.py** - Wrapper: action = base + α×residual
• **reward.py** - Custom milestone rewards

Type **"ready to train"** to upload & download.

Ask me anything about the reward design!${generatedNote}`
                    }]);
                }
            } catch (error) {
                console.error("Failed to load generated script:", error);
                setMessages([{
                    role: 'model',
                    content: `I couldn't generate the script for **${taskName}**. Make sure the video has been analyzed first.\n\nError: ${error.message || 'Unknown error'}`
                }]);
            }
            setScriptLoaded(true);
        };

        loadGeneratedScript();
    }, [taskName, scriptLoaded]);

    // Extract code blocks from assistant messages and update existing tabs or add new ones
    useEffect(() => {
        const lastMsg = messages[messages.length - 1];
        if (!lastMsg || lastMsg.role !== 'model') return;

        const codeBlockRegex = /```(\w+)?\n([\s\S]*?)```/g;
        let match;
        let updatedTabs = [...codeTabs];
        let hasUpdates = false;
        let lastUpdatedIndex = -1;

        while ((match = codeBlockRegex.exec(lastMsg.content)) !== null) {
            const language = match[1] || 'text';
            const code = match[2].trim();

            // Determine which existing file this code should update
            let targetFile = null;
            if (code.includes('def compute_reward')) targetFile = 'reward.py';
            else if (code.includes('REWARD_CONFIG') || code.includes('MILESTONES')) targetFile = 'config.py';
            else if (code.includes('class ResidualWrapper') || code.includes('residual_scale')) targetFile = 'residual.py';
            else if (code.includes('class BaselinePolicy') || code.includes('BCPolicy')) targetFile = 'baseline.py';
            else if (code.includes('def main') && code.includes('train')) targetFile = 'train.py';

            if (targetFile) {
                // Update existing tab in place
                const existingIdx = updatedTabs.findIndex(t => t.title === targetFile);
                if (existingIdx !== -1 && updatedTabs[existingIdx].code !== code) {
                    updatedTabs[existingIdx] = { ...updatedTabs[existingIdx], code };
                    hasUpdates = true;
                    lastUpdatedIndex = existingIdx;
                }
            } else {
                // Only create new tab for genuinely new snippets
                const snippetTitle = `snippet_${updatedTabs.length + 1}.${language === 'python' ? 'py' : language}`;
                if (!updatedTabs.find(t => t.code === code)) {
                    updatedTabs.push({ title: snippetTitle, language, code });
                    hasUpdates = true;
                    lastUpdatedIndex = updatedTabs.length - 1;
                }
            }
        }

        if (hasUpdates) {
            setCodeTabs(updatedTabs);
            if (lastUpdatedIndex >= 0) {
                setActiveTab(lastUpdatedIndex);
            }
        }
    }, [messages]);

    const handleSend = async () => {
        if (!input.trim() || isLoading) return;

        const userMsg = { role: 'user', content: input };
        setMessages(prev => [...prev, userMsg]);
        const userInput = input.toLowerCase().trim();
        setInput('');

        // Check for ready to train command
        if (userInput.includes('ready to train') || userInput.includes('ready') || userInput.includes('download') || userInput.includes('export')) {
            // Upload to S3
            setMessages(prev => [...prev, {
                role: 'model',
                content: `Uploading training files to cloud...`,
                isLoading: true
            }]);

            try {
                const trainCode = codeTabs.find(t => t.title === 'train.py')?.code || '';
                const configCode = codeTabs.find(t => t.title === 'config.py')?.code || '';
                const baselineCode = codeTabs.find(t => t.title === 'baseline.py')?.code || '';
                const residualCode = codeTabs.find(t => t.title === 'residual.py')?.code || '';
                const rewardCode = codeTabs.find(t => t.title === 'reward.py')?.code || '';

                const uploadRes = await fetch(`${API_BASE}/experiment/upload-training`, {
                    method: 'POST',
                    headers: { 'Content-Type': 'application/json' },
                    body: JSON.stringify({
                        task_name: taskName,
                        train_code: trainCode,
                        config_code: configCode,
                        baseline_code: baselineCode,
                        residual_code: residualCode,
                        reward_code: rewardCode
                    })
                });

                const uploadData = await uploadRes.json();

                if (uploadData.status === 'uploaded') {
                    setMessages(prev => {
                        const newMsgs = prev.filter(m => !m.isLoading);
                        return [...newMsgs, {
                            role: 'model',
                            content: `**Residual RL training files uploaded!**

**Location:** \`data/${taskName}/code/\`

**Files:**
• \`${uploadData.files.train.name}\` - Full training pipeline
• \`${uploadData.files.config.name}\` - All hyperparameters
• \`${uploadData.files.baseline.name}\` - BC base policy
• \`${uploadData.files.residual.name}\` - Residual wrapper
• \`${uploadData.files.reward.name}\` - Reward function (v${uploadData.reward_version})

**To run locally:**
\`\`\`bash
cd data/${taskName}/code/
python ${uploadData.files.train.name}
\`\`\`

Or download the files below:`,
                            showDownloadOptions: true
                        }];
                    });
                } else {
                    throw new Error(uploadData.detail || 'Upload failed');
                }
            } catch (error) {
                setMessages(prev => {
                    const newMsgs = prev.filter(m => !m.isLoading);
                    return [...newMsgs, {
                        role: 'model',
                        content: `Upload failed: ${error.message}\n\nYou can still download locally:`,
                        showDownloadOptions: true
                    }];
                });
            }
            return;
        }

        setIsLoading(true);

        try {
            const res = await fetch(`${API_BASE}/experiment/chat`, {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({
                    task_name: taskName,
                    message: userMsg.content,
                    history: messages.map(m => ({ role: m.role, content: m.content }))
                })
            });
            const data = await res.json();

            if (data.response) {
                setMessages(prev => [...prev, { role: 'model', content: data.response }]);
            } else {
                setMessages(prev => [...prev, { role: 'model', content: "Sorry, I encountered an error processing your request." }]);
            }
        } catch (error) {
            console.error(error);
            setMessages(prev => [...prev, { role: 'model', content: "Network error. Please try again." }]);
        } finally {
            setIsLoading(false);
        }
    };

    const downloadNotebook = () => {
        window.open(`${API_BASE}/experiment/notebook/${taskName}`, '_blank');
        setMessages(prev => [...prev, {
            role: 'model',
            content: `Downloading **train_${taskName}.ipynb**...\n\nTo use:\n1. Upload to [Google Colab](https://colab.research.google.com)\n2. Run cells to install dependencies\n3. Edit the \`compute_reward()\` function\n4. Start training!`
        }]);
    };

    const downloadPackage = () => {
        window.open(`${API_BASE}/experiment/package/${taskName}`, '_blank');
        setMessages(prev => [...prev, {
            role: 'model',
            content: `Downloading **${taskName}_training.zip**...\n\nContents:\n- \`train_${taskName}.py\` - Main training script\n- \`data/\` - Video and analysis\n- \`requirements.txt\` - Dependencies\n\nTo run:\n\`\`\`bash\npip install -r requirements.txt\npython train_${taskName}.py\n\`\`\``
        }]);
    };

    const handleKeyDown = (e) => {
        if (e.key === 'Enter' && !e.shiftKey) {
            e.preventDefault();
            handleSend();
        }
    };

    const copyToClipboard = (text) => {
        navigator.clipboard.writeText(text);
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
    };

    
    return (
        <div className="experiment-design">
            <header className="design-header">
                <button onClick={onBack} className="btn-back">
                    <ArrowLeft size={20} />
                    Back
                </button>
                <div className="header-title">
                    <h2>Experiment Designer</h2>
                    <span className="task-badge">{taskName}</span>
                </div>
            </header>

            <div className="design-grid">
                {/* Left: Video Reference */}
                <div className="video-column">
                    <div className="column-header">
                        <FileText size={16} />
                        <h3>Reference Video</h3>
                    </div>
                    <div className="video-card">
                        <video
                            ref={videoRef}
                            src={videoUrl || `${API_HOST}/data/${taskName}/labeled.mp4`}
                            controls
                            className="reference-video"
                        />
                    </div>
                </div>

                {/* Middle: Chat Interface */}
                <div className="chat-column">
                    <div className="column-header">
                        <Bot size={16} />
                        <h3>Assistant</h3>
                    </div>
                    <div className="messages-area">
                        {messages.map((msg, idx) => (
                            <div key={idx} className={`message ${msg.role}`}>
                                <div className="message-content">
                                    {msg.isLoading && (
                                        <div className="loading-indicator" style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '8px' }}>
                                            <Loader2 className="animate-spin" size={14} />
                                            <span style={{ fontSize: '0.8rem', color: 'var(--text-secondary)' }}>Generating script...</span>
                                        </div>
                                    )}
                                    <ReactMarkdown
                                        components={{
                                            code({ node, inline, className, children, ...props }) {
                                                const match = /language-(\w+)/.exec(className || '')
                                                return !inline && match ? (
                                                    <div className="code-block-preview">
                                                        <span>{match[1]} code (see right panel)</span>
                                                    </div>
                                                ) : (
                                                    <code className="inline-code" {...props}>
                                                        {children}
                                                    </code>
                                                )
                                            }
                                        }}
                                    >
                                        {msg.content}
                                    </ReactMarkdown>
                                    {msg.showDownloadOptions && (
                                        <div className="download-options">
                                            <button className="download-btn colab" onClick={downloadNotebook}>
                                                <Cloud size={18} />
                                                <div className="btn-text-content">
                                                    <span className="btn-title">Colab Notebook</span>
                                                    <span className="btn-desc">.ipynb for Google Colab</span>
                                                </div>
                                            </button>
                                            <button className="download-btn local" onClick={downloadPackage}>
                                                <Download size={18} />
                                                <div className="btn-text-content">
                                                    <span className="btn-title">Local Package</span>
                                                    <span className="btn-desc">.zip with all files</span>
                                                </div>
                                            </button>
                                        </div>
                                    )}
                                </div>
                            </div>
                        ))}
                        {isLoading && (
                            <div className="message model">
                                <div className="message-content typing">
                                    <Loader2 className="animate-spin" size={16} />
                                    <span>Thinking...</span>
                                </div>
                            </div>
                        )}
                        <div ref={messagesEndRef} />
                    </div>

                    <div className="input-area">
                        <textarea
                            value={input}
                            onChange={(e) => setInput(e.target.value)}
                            onKeyDown={handleKeyDown}
                            placeholder="Type a message..."
                            rows={1}
                        />
                        <button onClick={handleSend} disabled={isLoading || !input.trim()} className="btn-send">
                            <Send size={18} />
                        </button>
                    </div>
                </div>

                {/* Right: Code Viewer */}
                <div className="code-column">
                    <div className="column-header">
                        <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
                            <Code size={16} />
                            <h3>Code</h3>
                        </div>
                    </div>
                    {codeTabs.length > 0 ? (
                        <div className="code-viewer">
                            <div className="tabs-header">
                                {codeTabs.map((tab, idx) => (
                                    <button
                                        key={idx}
                                        className={`tab-btn ${activeTab === idx ? 'active' : ''}`}
                                        onClick={() => setActiveTab(idx)}
                                    >
                                        {tab.title}
                                    </button>
                                ))}
                            </div>
                            <div className="code-content">
                                <div className="code-actions">
                                    <span className="lang-badge">{codeTabs[activeTab]?.language}</span>
                                    <button
                                        className="btn-copy"
                                        onClick={() => copyToClipboard(codeTabs[activeTab]?.code)}
                                    >
                                        {copied ? <Check size={14} /> : <Copy size={14} />}
                                        {copied ? "Copied" : "Copy"}
                                    </button>
                                </div>
                                <pre>
                                    <code>{codeTabs[activeTab]?.code}</code>
                                </pre>
                            </div>
                        </div>
                    ) : (
                        <div className="empty-code-state">
                            <Loader2 className="animate-spin" size={32} />
                            <p>Generating training script...</p>
                            <span className="sub-text">Creating {taskName} with TD3 and custom reward function.</span>
                        </div>
                    )}
                </div>
            </div>

            <style>{`
                /* Minimal Scrollbar */
                * {
                    scrollbar-width: thin;
                    scrollbar-color: rgba(255, 255, 255, 0.1) transparent;
                }
                *::-webkit-scrollbar {
                    width: 4px;
                    height: 4px;
                }
                *::-webkit-scrollbar-track {
                    background: transparent;
                }
                *::-webkit-scrollbar-thumb {
                    background: rgba(255, 255, 255, 0.1);
                    border-radius: 2px;
                }
                *::-webkit-scrollbar-thumb:hover {
                    background: rgba(255, 255, 255, 0.2);
                }

                .experiment-design {
                    display: flex;
                flex-direction: column;
                height: 100vh;
                background: var(--bg-main);
                overflow: hidden;
                }
                .design-header {
                    display: flex;
                align-items: center;
                gap: 16px;
                padding: 12px 24px;
                background: var(--bg-card);
                border-bottom: 1px solid var(--border-color);
                height: 60px;
                }
                .btn-back {
                    display: flex;
                align-items: center;
                gap: 8px;
                background: transparent;
                border: none;
                color: var(--text-secondary);
                cursor: pointer;
                font-size: 0.9rem;
                padding: 8px;
                border-radius: 8px;
                transition: all 0.2s;
                }
                .btn-back:hover {
                    background: var(--bg-secondary);
                color: white;
                }
                .header-title {
                    display: flex;
                align-items: center;
                gap: 12px;
                }
                .header-title h2 {margin: 0; font-size: 1.1rem; }
                .task-badge {
                    background: var(--bg-secondary);
                padding: 2px 8px;
                border-radius: 4px;
                font-size: 0.75rem;
                color: var(--text-secondary);
                font-family: monospace;
                }

                /* 3-Column Layout */
                .design-grid {
                    display: grid;
                grid-template-columns: 350px 450px 1fr;
                flex: 1;
                min-height: 0;
                overflow: hidden;
                }

                .column-header {
                    display: flex;
                align-items: center;
                gap: 8px;
                padding: 12px 16px;
                border-bottom: 1px solid var(--border-color);
                background: var(--bg-secondary);
                color: var(--text-secondary);
                font-size: 0.8rem;
                text-transform: uppercase;
                letter-spacing: 0.05em;
                }
                .column-header h3 {margin: 0; font-size: inherit; font-weight: 600; }

                /* Video Column */
                .video-column {
                    display: flex;
                flex-direction: column;
                border-right: 1px solid var(--border-color);
                background: black;
                }
                .video-card {
                    padding: 16px;
                display: flex;
                align-items: center;
                justify-content: center;
                flex: 1;
                }
                .reference-video {width: 100%; max-height: 100%; border-radius: 8px; }

                /* Chat Column */
                .chat-column {
                    display: flex;
                flex-direction: column;
                border-right: 1px solid var(--border-color);
                background: var(--bg-card);
                overflow: hidden;
                }
                .messages-area {
                    flex: 1;
                overflow-y: auto;
                padding: 16px;
                display: flex;
                flex-direction: column;
                gap: 16px;
                }
                .message {
                    display: flex;
                flex-direction: column;
                gap: 4px;
                max-width: 90%;
                }
                .message.user {align - self: flex-end; align-items: flex-end; }
                .message.model {align - self: flex-start; }

                .message-content {
                    background: var(--bg-secondary);
                padding: 10px 14px;
                border-radius: 12px;
                color: var(--text-main);
                font-size: 0.9rem;
                line-height: 1.5;
                }
                .message.user .message-content {
                    background: #3b82f6;
                color: white;
                border-bottom-right-radius: 4px;
                }
                .message.model .message-content {
                    border - bottom - left - radius: 4px;
                }
                .input-area {
                    padding: 12px 16px;
                border-top: 1px solid var(--border-color);
                display: flex;
                gap: 8px;
                background: var(--bg-card);
                }
                .input-area textarea {
                    flex: 1;
                background: var(--bg-secondary);
                border: 1px solid var(--border-color);
                border-radius: 8px;
                padding: 10px;
                color: white;
                resize: none;
                font-family: inherit;
                min-height: 40px;
                max-height: 100px;
                font-size: 0.9rem;
                }
                .input-area textarea:focus {outline: none; border-color: #3b82f6; }
                .btn-send {
                    background: #3b82f6;
                border: none;
                color: white;
                width: 40px;
                height: 40px;
                border-radius: 8px;
                cursor: pointer;
                display: flex;
                align-items: center;
                justify-content: center;
                }
                .btn-send:hover:not(:disabled) {background: #2563eb; }
                .btn-send:disabled {opacity: 0.5; cursor: not-allowed; }

                /* Code Column */
                .code-column {
                    display: flex;
                flex-direction: column;
                background: #1e1e1e;
                min-width: 0; 
                overflow: hidden;
                }
                .code-viewer {
                    display: flex;
                flex-direction: column;
                flex: 1;
                min-height: 0;
                }
                .tabs-header {
                    display: flex;
                background: #252526;
                overflow-x: auto;
                }
                .tab-btn {
                    padding: 10px 16px;
                background: transparent;
                border: none;
                color: var(--text-secondary);
                cursor: pointer;
                font-size: 0.85rem;
                border-right: 1px solid #333;
                white-space: nowrap;
                }
                .tab-btn:hover {background: #2d2d2d; color: white; }
                .tab-btn.active {
                    background: #1e1e1e;
                color: white;
                border-top: 2px solid #3b82f6;
                }
                .code-content {
                    flex: 1;
                position: relative;
                overflow: auto;
                padding: 16px;
                }
                .code-actions {
                    position: absolute;
                top: 16px;
                right: 16px;
                display: flex;
                gap: 8px;
                align-items: center;
                }
                .lang-badge {
                    font - size: 0.7rem;
                color: var(--text-secondary);
                text-transform: uppercase;
                }
                .btn-copy {
                    background: rgba(255,255,255,0.1);
                border: none;
                color: white;
                padding: 4px 8px;
                border-radius: 4px;
                cursor: pointer;
                display: flex;
                align-items: center;
                gap: 6px;
                font-size: 0.75rem;
                transition: background 0.2s;
                }
                .btn-copy:hover {background: rgba(255,255,255,0.2); }

                .code-content pre {margin: 0; font-family: 'Consolas', 'Monaco', monospace; font-size: 0.9rem; line-height: 1.5; color: #d4d4d4; }

                .empty-code-state {
                    display: flex;
                flex-direction: column;
                align-items: center;
                justify-content: center;
                flex: 1;
                color: var(--text-secondary);
                opacity: 0.5;
                }
                .empty-code-state p {margin: 16px 0 8px 0; font-size: 1.1rem; font-weight: 500; }
                .empty-code-state .sub-text {font - size: 0.85rem; }

                .code-block-preview {
                    background: rgba(0,0,0,0.2);
                padding: 8px;
                border-radius: 6px;
                border: 1px dashed var(--border-color);
                font-size: 0.8rem;
                color: var(--text-secondary);
                cursor: default;
                }

                /* Download Options */
                .download-options {
                    display: flex;
                    gap: 12px;
                    margin-top: 12px;
                }
                .download-btn {
                    display: flex;
                    align-items: center;
                    gap: 10px;
                    padding: 12px 16px;
                    border: 1px solid var(--border-color);
                    border-radius: 8px;
                    background: var(--bg-secondary);
                    color: white;
                    cursor: pointer;
                    transition: all 0.2s;
                    flex: 1;
                }
                .download-btn:hover {
                    border-color: #3b82f6;
                    background: rgba(59, 130, 246, 0.1);
                }
                .download-btn.colab {
                    border-color: #f59e0b;
                }
                .download-btn.colab:hover {
                    border-color: #f59e0b;
                    background: rgba(245, 158, 11, 0.1);
                }
                .download-btn .btn-text-content {
                    display: flex;
                    flex-direction: column;
                    align-items: flex-start;
                    gap: 2px;
                }
                .download-btn .btn-title {
                    font-weight: 600;
                    font-size: 0.9rem;
                }
                .download-btn .btn-desc {
                    font-size: 0.75rem;
                    color: var(--text-secondary);
                }

                /* Spin Animation */
                @keyframes spin {
                    from { transform: rotate(0deg); }
                    to { transform: rotate(360deg); }
                }
                .animate-spin {
                    animation: spin 1s linear infinite;
                }
            `}</style >
        </div >
    );
}
